# **PERKENALAN**

Nama : Sutisna

Non Grade Challenge 3 SQL

Akses data-data pada https://www.kaggle.com/anlgrbz/student-demographics-online-education-dataoulad kecuali studentVle.csv

import library yang dibutuhkan

In [15]:
from pathlib import Path
Path('h8dsft_SQL.db').touch()

Membuat koneksi antara pythoin dengan SQL Database dan diberikan nama database tersebut 'h8dsft_SQL.db'

In [16]:
import sqlite3
conn = sqlite3.connect('h8dsft_SQL.db')
c = conn.cursor()

Membuat table 'assessment' dari data assessment.csv yang sudah di download dan menyimpannya di database

In [47]:
import pandas as pd
users = pd.read_csv('assessments.csv')
# write the data to a sqlite table
users.to_sql('assessments', conn, if_exists='append', index = False)

Kita akan melihat kolom-kolom apa saja yang ada di tabel 'assessment'

In [48]:
c.execute('''SELECT * FROM assessments''').fetchall() # [(1, 'pokerkid'), (2, 'crazyken')]

[('AAA', '2013J', 1752, 'TMA', 19.0, 10.0),
 ('AAA', '2013J', 1753, 'TMA', 54.0, 20.0),
 ('AAA', '2013J', 1754, 'TMA', 117.0, 20.0),
 ('AAA', '2013J', 1755, 'TMA', 166.0, 20.0),
 ('AAA', '2013J', 1756, 'TMA', 215.0, 30.0),
 ('AAA', '2013J', 1757, 'Exam', None, 100.0),
 ('AAA', '2014J', 1758, 'TMA', 19.0, 10.0),
 ('AAA', '2014J', 1759, 'TMA', 54.0, 20.0),
 ('AAA', '2014J', 1760, 'TMA', 117.0, 20.0),
 ('AAA', '2014J', 1761, 'TMA', 166.0, 20.0),
 ('AAA', '2014J', 1762, 'TMA', 215.0, 30.0),
 ('AAA', '2014J', 1763, 'Exam', None, 100.0),
 ('BBB', '2013B', 14991, 'CMA', 54.0, 1.0),
 ('BBB', '2013B', 14992, 'CMA', 89.0, 1.0),
 ('BBB', '2013B', 14993, 'CMA', 124.0, 1.0),
 ('BBB', '2013B', 14994, 'CMA', 159.0, 1.0),
 ('BBB', '2013B', 14995, 'CMA', 187.0, 1.0),
 ('BBB', '2013B', 14984, 'TMA', 19.0, 5.0),
 ('BBB', '2013B', 14985, 'TMA', 47.0, 18.0),
 ('BBB', '2013B', 14986, 'TMA', 89.0, 18.0),
 ('BBB', '2013B', 14987, 'TMA', 124.0, 18.0),
 ('BBB', '2013B', 14988, 'TMA', 159.0, 18.0),
 ('BBB', '2013B', 14989, 'TMA', 187.0, 18.0),
 ('BBB', '2013B', 14990, 'Exam', None, 100.0),
 ('BBB', '2013J', 15003, 'CMA', 54.0, 1.0),
 ('BBB', '2013J', 15004, 'CMA', 96.0, 1.0),
 ('BBB', '2013J', 15005, 'CMA', 131.0, 1.0),
 ('BBB', '2013J', 15006, 'CMA', 166.0, 1.0),
 ('BBB', '2013J', 15007, 'CMA', 208.0, 1.0),
 ('BBB', '2013J', 14996, 'TMA', 19.0, 5.0),
 ('BBB', '2013J', 14997, 'TMA', 47.0, 18.0),
 ('BBB', '2013J', 14998, 'TMA', 96.0, 18.0),
 ('BBB', '2013J', 14999, 'TMA', 131.0, 18.0),
 ('BBB', '2013J', 15000, 'TMA', 166.0, 18.0),
 ('BBB', '2013J', 15001, 'TMA', 208.0, 18.0),
 ('BBB', '2013J', 15002, 'Exam', None, 100.0),
 ('BBB', '2014B', 15015, 'CMA', 47.0, 1.0),
 ('BBB', '2014B', 15016, 'CMA', 82.0, 1.0),
 ('BBB', '2014B', 15017, 'CMA', 117.0, 1.0),
 ('BBB', '2014B', 15018, 'CMA', 152.0, 1.0),
 ('BBB', '2014B', 15019, 'CMA', 194.0, 1.0),
 ('BBB', '2014B', 15008, 'TMA', 12.0, 5.0),
 ('BBB', '2014B', 15009, 'TMA', 40.0, 18.0),
 ('BBB', '2014B', 15010, 'TMA', 82.0, 18.0),
 ('BBB', '2014B', 15011, 'TMA', 117.0, 18.0),
 ('BBB', '2014B', 15012, 'TMA', 152.0, 18.0),
 ('BBB', '2014B', 15013, 'TMA', 194.0, 18.0),
 ('BBB', '2014B', 15014, 'Exam', None, 100.0),
 ('BBB', '2014J', 15020, 'TMA', 19.0, 0.0),
 ('BBB', '2014J', 15021, 'TMA', 54.0, 10.0),
 ('BBB', '2014J', 15022, 'TMA', 110.0, 20.0),
 ('BBB', '2014J', 15023, 'TMA', 152.0, 35.0),
 ('BBB', '2014J', 15024, 'TMA', 201.0, 35.0),
 ('BBB', '2014J', 15025, 'Exam', None, 100.0),
 ('CCC', '2014B', 24286, 'CMA', 18.0, 2.0),
 ('CCC', '2014B', 24287, 'CMA', 67.0, 7.0),
 ('CCC', '2014B', 24288, 'CMA', 137.0, 8.0),
 ('CCC', '2014B', 24289, 'CMA', 207.0, 8.0),
 ('CCC', '2014B', 24282, 'TMA', 32.0, 9.0),
 ('CCC', '2014B', 24283, 'TMA', 102.0, 22.0),
 ('CCC', '2014B', 24284, 'TMA', 151.0, 22.0),
 ('CCC', '2014B', 24285, 'TMA', 200.0, 22.0),
 ('CCC', '2014B', 24290, 'Exam', None, 100.0),
 ('CCC', '2014B', 40087, 'Exam', None, 100.0),
 ('CCC', '2014J', 24295, 'CMA', 18.0, 2.0),
 ('CCC', '2014J', 24296, 'CMA', 67.0, 7.0),
 ('CCC', '2014J', 24297, 'CMA', 144.0, 8.0),
 ('CCC', '2014J', 24298, 'CMA', 214.0, 8.0),
 ('CCC', '2014J', 24291, 'TMA', 32.0, 9.0),
 ('CCC', '2014J', 24292, 'TMA', 109.0, 22.0),
 ('CCC', '2014J', 24293, 'TMA', 158.0, 22.0),
 ('CCC', '2014J', 24294, 'TMA', 207.0, 22.0),
 ('CCC', '2014J', 24299, 'Exam', None, 100.0),
 ('CCC', '2014J', 40088, 'Exam', None, 100.0),
 ('DDD', '2013B', 25341, 'CMA', 23.0, 2.0),
 ('DDD', '2013B', 25342, 'CMA', 51.0, 3.0),
 ('DDD', '2013B', 25343, 'CMA', 79.0, 3.0),
 ('DDD', '2013B', 25344, 'CMA', 114.0, 4.0),
 ('DDD', '2013B', 25345, 'CMA', 149.0, 4.0),
 ('DDD', '2013B', 25346, 'CMA', 170.0, 3.0),
 ('DDD', '2013B', 25347, 'CMA', 206.0, 6.0),
 ('DDD', '2013B', 25334, 'TMA', 25.0, 7.5),
 ('DDD', '2013B', 25335, 'TMA', 53.0, 10.0),
 ('DDD', '2013B', 25336, 'TMA', 81.0, 12.5),
 ('DDD', '2013B', 25337, 'TMA', 116.0, 15.0),
 ('DDD', '2013B', 25338, 'TMA', 151.0, 15.0),
 ('DDD', '2013B', 25339, 'TMA', 200.0, 15.0),
 ('DDD', '2013B', 25340, 'Exam', 240.0, 100.0),
 ('DDD', '2013J', 25348, 'TMA', 25.0, 10.0),
 ('DDD', '2013J', 25349, 'TMA', 53.0, 12.5),
 ('DDD', '2013J', 25350, 'TMA', 88.0, 17.5),
 ('DDD', '2013J', 25351, 'TMA', 123.0, 20.0),
 ('DDD', '2013J', 25352, 'TMA', 165.0, 20.0),
 ('DDD', '2013J', 25353, 'TMA', 207.0, 20.0),
 ('DDD', '2013J', 25354, 'Exam', 261.0, 100.0),
 ('DDD', '2014B', 25355, 'TMA', 25.0, 10.0),
 ('DDD', '2014B', 25356, 'TMA', 53.0, 12.5),
 ('DDD', '2014B', 25357, 'TMA', 74.0, 17.5),
 ('DDD', '2014B', 25358, 'TMA', 116.0, 20.0),
 ('DDD', '2014B', 25359, 'TMA', 158.0, 20.0),
 ('DDD', '2014B', 25360, 'TMA', 200.0, 20.0),
 ('DDD', '2014B', 25361, 'Exam', 241.0, 100.0),
 ('DDD', '2014J', 25362, 'TMA', 20.0, 5.0),
 ('DDD', '2014J', 25363, 'TMA', 41.0, 10.0),
 ('DDD', '2014J', 25364, 'TMA', 62.0, 10.0),
 ('DDD', '2014J', 25365, 'TMA', 111.0, 25.0),
 ('DDD', '2014J', 25366, 'TMA', 146.0, 25.0),
 ('DDD', '2014J', 25367, 'TMA', 195.0, 25.0),
 ('DDD', '2014J', 25368, 'Exam', None, 100.0),
 ('EEE', '2013J', 30709, 'TMA', 33.0, 16.0),
 ('EEE', '2013J', 30710, 'TMA', 68.0, 28.0),
 ('EEE', '2013J', 30711, 'TMA', 124.0, 28.0),
 ('EEE', '2013J', 30712, 'TMA', 159.0, 28.0),
 ('EEE', '2013J', 30713, 'Exam', 235.0, 100.0),
 ('EEE', '2014B', 30714, 'TMA', 33.0, 16.0),
 ('EEE', '2014B', 30715, 'TMA', 68.0, 28.0),
 ('EEE', '2014B', 30716, 'TMA', 117.0, 28.0),
 ('EEE', '2014B', 30717, 'TMA', 152.0, 28.0),
 ('EEE', '2014B', 30718, 'Exam', 228.0, 100.0),
 ('EEE', '2014J', 30719, 'TMA', 33.0, 16.0),
 ('EEE', '2014J', 30720, 'TMA', 68.0, 28.0),
 ('EEE', '2014J', 30721, 'TMA', 131.0, 28.0),
 ('EEE', '2014J', 30722, 'TMA', 166.0, 28.0),
 ('EEE', '2014J', 30723, 'Exam', 235.0, 100.0),
 ('FFF', '2013B', 34865, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34866, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34867, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34868, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34869, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34871, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34870, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34860, 'TMA', 19.0, 12.5),
 ('FFF', '2013B', 34861, 'TMA', 47.0, 12.5),
 ('FFF', '2013B', 34862, 'TMA', 89.0, 25.0),
 ('FFF', '2013B', 34863, 'TMA', 131.0, 25.0),
 ('FFF', '2013B', 34864, 'TMA', 166.0, 25.0),
 ('FFF', '2013B', 34872, 'Exam', 222.0, 100.0),
 ('FFF', '2013J', 34878, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34879, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34880, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34881, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34882, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34884, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34883, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34873, 'TMA', 19.0, 12.5),
 ('FFF', '2013J', 34874, 'TMA', 47.0, 12.5),
 ('FFF', '2013J', 34875, 'TMA', 96.0, 25.0),
 ('FFF', '2013J', 34876, 'TMA', 131.0, 25.0),
 ('FFF', '2013J', 34877, 'TMA', 173.0, 25.0),
 ('FFF', '2013J', 34885, 'Exam', 236.0, 100.0),
 ('FFF', '2014B', 34891, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34892, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34893, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34894, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34895, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34897, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34896, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34886, 'TMA', 24.0, 12.5),
 ('FFF', '2014B', 34887, 'TMA', 52.0, 12.5),
 ('FFF', '2014B', 34888, 'TMA', 87.0, 25.0),
 ('FFF', '2014B', 34889, 'TMA', 129.0, 25.0),
 ('FFF', '2014B', 34890, 'TMA', 171.0, 25.0),
 ('FFF', '2014B', 34898, 'Exam', 227.0, 100.0),
 ('FFF', '2014J', 34904, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34905, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34906, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34907, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34908, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34910, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34909, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34899, 'TMA', 24.0, 12.5),
 ('FFF', '2014J', 34900, 'TMA', 52.0, 12.5),
 ('FFF', '2014J', 34901, 'TMA', 94.0, 25.0),
 ('FFF', '2014J', 34902, 'TMA', 136.0, 25.0),
 ('FFF', '2014J', 34903, 'TMA', 199.0, 25.0),
 ('FFF', '2014J', 34911, 'Exam', 241.0, 100.0),
 ('GGG', '2013J', 37418, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37419, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37420, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37421, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37422, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37423, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37415, 'TMA', 61.0, 0.0),
 ('GGG', '2013J', 37416, 'TMA', 124.0, 0.0),
 ('GGG', '2013J', 37417, 'TMA', 173.0, 0.0),
 ('GGG', '2013J', 37424, 'Exam', 229.0, 100.0),
 ('GGG', '2014B', 37428, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37429, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37430, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37431, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37432, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37433, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37425, 'TMA', 61.0, 0.0),
 ('GGG', '2014B', 37426, 'TMA', 117.0, 0.0),
 ('GGG', '2014B', 37427, 'TMA', 166.0, 0.0),
 ('GGG', '2014B', 37434, 'Exam', 222.0, 100.0),
 ('GGG', '2014J', 37438, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37439, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37440, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37441, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37442, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37443, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37435, 'TMA', 61.0, 0.0),
 ('GGG', '2014J', 37436, 'TMA', 124.0, 0.0),
 ('GGG', '2014J', 37437, 'TMA', 173.0, 0.0),
 ('GGG', '2014J', 37444, 'Exam', 229.0, 100.0),
 ('AAA', '2013J', 1752, 'TMA', 19.0, 10.0),
 ('AAA', '2013J', 1753, 'TMA', 54.0, 20.0),
 ('AAA', '2013J', 1754, 'TMA', 117.0, 20.0),
 ('AAA', '2013J', 1755, 'TMA', 166.0, 20.0),
 ('AAA', '2013J', 1756, 'TMA', 215.0, 30.0),
 ('AAA', '2013J', 1757, 'Exam', None, 100.0),
 ('AAA', '2014J', 1758, 'TMA', 19.0, 10.0),
 ('AAA', '2014J', 1759, 'TMA', 54.0, 20.0),
 ('AAA', '2014J', 1760, 'TMA', 117.0, 20.0),
 ('AAA', '2014J', 1761, 'TMA', 166.0, 20.0),
 ('AAA', '2014J', 1762, 'TMA', 215.0, 30.0),
 ('AAA', '2014J', 1763, 'Exam', None, 100.0),
 ('BBB', '2013B', 14991, 'CMA', 54.0, 1.0),
 ('BBB', '2013B', 14992, 'CMA', 89.0, 1.0),
 ('BBB', '2013B', 14993, 'CMA', 124.0, 1.0),
 ('BBB', '2013B', 14994, 'CMA', 159.0, 1.0),
 ('BBB', '2013B', 14995, 'CMA', 187.0, 1.0),
 ('BBB', '2013B', 14984, 'TMA', 19.0, 5.0),
 ('BBB', '2013B', 14985, 'TMA', 47.0, 18.0),
 ('BBB', '2013B', 14986, 'TMA', 89.0, 18.0),
 ('BBB', '2013B', 14987, 'TMA', 124.0, 18.0),
 ('BBB', '2013B', 14988, 'TMA', 159.0, 18.0),
 ('BBB', '2013B', 14989, 'TMA', 187.0, 18.0),
 ('BBB', '2013B', 14990, 'Exam', None, 100.0),
 ('BBB', '2013J', 15003, 'CMA', 54.0, 1.0),
 ('BBB', '2013J', 15004, 'CMA', 96.0, 1.0),
 ('BBB', '2013J', 15005, 'CMA', 131.0, 1.0),
 ('BBB', '2013J', 15006, 'CMA', 166.0, 1.0),
 ('BBB', '2013J', 15007, 'CMA', 208.0, 1.0),
 ('BBB', '2013J', 14996, 'TMA', 19.0, 5.0),
 ('BBB', '2013J', 14997, 'TMA', 47.0, 18.0),
 ('BBB', '2013J', 14998, 'TMA', 96.0, 18.0),
 ('BBB', '2013J', 14999, 'TMA', 131.0, 18.0),
 ('BBB', '2013J', 15000, 'TMA', 166.0, 18.0),
 ('BBB', '2013J', 15001, 'TMA', 208.0, 18.0),
 ('BBB', '2013J', 15002, 'Exam', None, 100.0),
 ('BBB', '2014B', 15015, 'CMA', 47.0, 1.0),
 ('BBB', '2014B', 15016, 'CMA', 82.0, 1.0),
 ('BBB', '2014B', 15017, 'CMA', 117.0, 1.0),
 ('BBB', '2014B', 15018, 'CMA', 152.0, 1.0),
 ('BBB', '2014B', 15019, 'CMA', 194.0, 1.0),
 ('BBB', '2014B', 15008, 'TMA', 12.0, 5.0),
 ('BBB', '2014B', 15009, 'TMA', 40.0, 18.0),
 ('BBB', '2014B', 15010, 'TMA', 82.0, 18.0),
 ('BBB', '2014B', 15011, 'TMA', 117.0, 18.0),
 ('BBB', '2014B', 15012, 'TMA', 152.0, 18.0),
 ('BBB', '2014B', 15013, 'TMA', 194.0, 18.0),
 ('BBB', '2014B', 15014, 'Exam', None, 100.0),
 ('BBB', '2014J', 15020, 'TMA', 19.0, 0.0),
 ('BBB', '2014J', 15021, 'TMA', 54.0, 10.0),
 ('BBB', '2014J', 15022, 'TMA', 110.0, 20.0),
 ('BBB', '2014J', 15023, 'TMA', 152.0, 35.0),
 ('BBB', '2014J', 15024, 'TMA', 201.0, 35.0),
 ('BBB', '2014J', 15025, 'Exam', None, 100.0),
 ('CCC', '2014B', 24286, 'CMA', 18.0, 2.0),
 ('CCC', '2014B', 24287, 'CMA', 67.0, 7.0),
 ('CCC', '2014B', 24288, 'CMA', 137.0, 8.0),
 ('CCC', '2014B', 24289, 'CMA', 207.0, 8.0),
 ('CCC', '2014B', 24282, 'TMA', 32.0, 9.0),
 ('CCC', '2014B', 24283, 'TMA', 102.0, 22.0),
 ('CCC', '2014B', 24284, 'TMA', 151.0, 22.0),
 ('CCC', '2014B', 24285, 'TMA', 200.0, 22.0),
 ('CCC', '2014B', 24290, 'Exam', None, 100.0),
 ('CCC', '2014B', 40087, 'Exam', None, 100.0),
 ('CCC', '2014J', 24295, 'CMA', 18.0, 2.0),
 ('CCC', '2014J', 24296, 'CMA', 67.0, 7.0),
 ('CCC', '2014J', 24297, 'CMA', 144.0, 8.0),
 ('CCC', '2014J', 24298, 'CMA', 214.0, 8.0),
 ('CCC', '2014J', 24291, 'TMA', 32.0, 9.0),
 ('CCC', '2014J', 24292, 'TMA', 109.0, 22.0),
 ('CCC', '2014J', 24293, 'TMA', 158.0, 22.0),
 ('CCC', '2014J', 24294, 'TMA', 207.0, 22.0),
 ('CCC', '2014J', 24299, 'Exam', None, 100.0),
 ('CCC', '2014J', 40088, 'Exam', None, 100.0),
 ('DDD', '2013B', 25341, 'CMA', 23.0, 2.0),
 ('DDD', '2013B', 25342, 'CMA', 51.0, 3.0),
 ('DDD', '2013B', 25343, 'CMA', 79.0, 3.0),
 ('DDD', '2013B', 25344, 'CMA', 114.0, 4.0),
 ('DDD', '2013B', 25345, 'CMA', 149.0, 4.0),
 ('DDD', '2013B', 25346, 'CMA', 170.0, 3.0),
 ('DDD', '2013B', 25347, 'CMA', 206.0, 6.0),
 ('DDD', '2013B', 25334, 'TMA', 25.0, 7.5),
 ('DDD', '2013B', 25335, 'TMA', 53.0, 10.0),
 ('DDD', '2013B', 25336, 'TMA', 81.0, 12.5),
 ('DDD', '2013B', 25337, 'TMA', 116.0, 15.0),
 ('DDD', '2013B', 25338, 'TMA', 151.0, 15.0),
 ('DDD', '2013B', 25339, 'TMA', 200.0, 15.0),
 ('DDD', '2013B', 25340, 'Exam', 240.0, 100.0),
 ('DDD', '2013J', 25348, 'TMA', 25.0, 10.0),
 ('DDD', '2013J', 25349, 'TMA', 53.0, 12.5),
 ('DDD', '2013J', 25350, 'TMA', 88.0, 17.5),
 ('DDD', '2013J', 25351, 'TMA', 123.0, 20.0),
 ('DDD', '2013J', 25352, 'TMA', 165.0, 20.0),
 ('DDD', '2013J', 25353, 'TMA', 207.0, 20.0),
 ('DDD', '2013J', 25354, 'Exam', 261.0, 100.0),
 ('DDD', '2014B', 25355, 'TMA', 25.0, 10.0),
 ('DDD', '2014B', 25356, 'TMA', 53.0, 12.5),
 ('DDD', '2014B', 25357, 'TMA', 74.0, 17.5),
 ('DDD', '2014B', 25358, 'TMA', 116.0, 20.0),
 ('DDD', '2014B', 25359, 'TMA', 158.0, 20.0),
 ('DDD', '2014B', 25360, 'TMA', 200.0, 20.0),
 ('DDD', '2014B', 25361, 'Exam', 241.0, 100.0),
 ('DDD', '2014J', 25362, 'TMA', 20.0, 5.0),
 ('DDD', '2014J', 25363, 'TMA', 41.0, 10.0),
 ('DDD', '2014J', 25364, 'TMA', 62.0, 10.0),
 ('DDD', '2014J', 25365, 'TMA', 111.0, 25.0),
 ('DDD', '2014J', 25366, 'TMA', 146.0, 25.0),
 ('DDD', '2014J', 25367, 'TMA', 195.0, 25.0),
 ('DDD', '2014J', 25368, 'Exam', None, 100.0),
 ('EEE', '2013J', 30709, 'TMA', 33.0, 16.0),
 ('EEE', '2013J', 30710, 'TMA', 68.0, 28.0),
 ('EEE', '2013J', 30711, 'TMA', 124.0, 28.0),
 ('EEE', '2013J', 30712, 'TMA', 159.0, 28.0),
 ('EEE', '2013J', 30713, 'Exam', 235.0, 100.0),
 ('EEE', '2014B', 30714, 'TMA', 33.0, 16.0),
 ('EEE', '2014B', 30715, 'TMA', 68.0, 28.0),
 ('EEE', '2014B', 30716, 'TMA', 117.0, 28.0),
 ('EEE', '2014B', 30717, 'TMA', 152.0, 28.0),
 ('EEE', '2014B', 30718, 'Exam', 228.0, 100.0),
 ('EEE', '2014J', 30719, 'TMA', 33.0, 16.0),
 ('EEE', '2014J', 30720, 'TMA', 68.0, 28.0),
 ('EEE', '2014J', 30721, 'TMA', 131.0, 28.0),
 ('EEE', '2014J', 30722, 'TMA', 166.0, 28.0),
 ('EEE', '2014J', 30723, 'Exam', 235.0, 100.0),
 ('FFF', '2013B', 34865, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34866, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34867, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34868, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34869, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34871, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34870, 'CMA', 222.0, 0.0),
 ('FFF', '2013B', 34860, 'TMA', 19.0, 12.5),
 ('FFF', '2013B', 34861, 'TMA', 47.0, 12.5),
 ('FFF', '2013B', 34862, 'TMA', 89.0, 25.0),
 ('FFF', '2013B', 34863, 'TMA', 131.0, 25.0),
 ('FFF', '2013B', 34864, 'TMA', 166.0, 25.0),
 ('FFF', '2013B', 34872, 'Exam', 222.0, 100.0),
 ('FFF', '2013J', 34878, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34879, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34880, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34881, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34882, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34884, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34883, 'CMA', 236.0, 0.0),
 ('FFF', '2013J', 34873, 'TMA', 19.0, 12.5),
 ('FFF', '2013J', 34874, 'TMA', 47.0, 12.5),
 ('FFF', '2013J', 34875, 'TMA', 96.0, 25.0),
 ('FFF', '2013J', 34876, 'TMA', 131.0, 25.0),
 ('FFF', '2013J', 34877, 'TMA', 173.0, 25.0),
 ('FFF', '2013J', 34885, 'Exam', 236.0, 100.0),
 ('FFF', '2014B', 34891, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34892, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34893, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34894, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34895, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34897, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34896, 'CMA', 227.0, 0.0),
 ('FFF', '2014B', 34886, 'TMA', 24.0, 12.5),
 ('FFF', '2014B', 34887, 'TMA', 52.0, 12.5),
 ('FFF', '2014B', 34888, 'TMA', 87.0, 25.0),
 ('FFF', '2014B', 34889, 'TMA', 129.0, 25.0),
 ('FFF', '2014B', 34890, 'TMA', 171.0, 25.0),
 ('FFF', '2014B', 34898, 'Exam', 227.0, 100.0),
 ('FFF', '2014J', 34904, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34905, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34906, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34907, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34908, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34910, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34909, 'CMA', 241.0, 0.0),
 ('FFF', '2014J', 34899, 'TMA', 24.0, 12.5),
 ('FFF', '2014J', 34900, 'TMA', 52.0, 12.5),
 ('FFF', '2014J', 34901, 'TMA', 94.0, 25.0),
 ('FFF', '2014J', 34902, 'TMA', 136.0, 25.0),
 ('FFF', '2014J', 34903, 'TMA', 199.0, 25.0),
 ('FFF', '2014J', 34911, 'Exam', 241.0, 100.0),
 ('GGG', '2013J', 37418, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37419, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37420, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37421, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37422, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37423, 'CMA', 229.0, 0.0),
 ('GGG', '2013J', 37415, 'TMA', 61.0, 0.0),
 ('GGG', '2013J', 37416, 'TMA', 124.0, 0.0),
 ('GGG', '2013J', 37417, 'TMA', 173.0, 0.0),
 ('GGG', '2013J', 37424, 'Exam', 229.0, 100.0),
 ('GGG', '2014B', 37428, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37429, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37430, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37431, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37432, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37433, 'CMA', 222.0, 0.0),
 ('GGG', '2014B', 37425, 'TMA', 61.0, 0.0),
 ('GGG', '2014B', 37426, 'TMA', 117.0, 0.0),
 ('GGG', '2014B', 37427, 'TMA', 166.0, 0.0),
 ('GGG', '2014B', 37434, 'Exam', 222.0, 100.0),
 ('GGG', '2014J', 37438, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37439, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37440, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37441, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37442, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37443, 'CMA', 229.0, 0.0),
 ('GGG', '2014J', 37435, 'TMA', 61.0, 0.0),
 ('GGG', '2014J', 37436, 'TMA', 124.0, 0.0),
 ('GGG', '2014J', 37437, 'TMA', 173.0, 0.0),
 ('GGG', '2014J', 37444, 'Exam', 229.0, 100.0),
 ('AAA', '2013J', 1752, 'TMA', 19.0, 10.0),
 ('AAA', '2013J', 1753, 'TMA', 54.0, 20.0),
 ('AAA', '2013J', 1754, 'TMA', 117.0, 20.0),
 ('AAA', '2013J', 1755, 'TMA', 166.0, 20.0),
 ('AAA', '2013J', 1756, 'TMA', 215.0, 30.0),
 ('AAA', '2013J', 1757, 'Exam', None, 100.0),
 ('AAA', '2014J', 1758, 'TMA', 19.0, 10.0),
 ('AAA', '2014J', 1759, 'TMA', 54.0, 20.0),
 ('AAA', '2014J', 1760, 'TMA', 117.0, 20.0),
 ('AAA', '2014J', 1761, 'TMA', 166.0, 20.0),
 ('AAA', '2014J', 1762, 'TMA', 215.0, 30.0),
 ('AAA', '2014J', 1763, 'Exam', None, 100.0),
 ('BBB', '2013B', 14991, 'CMA', 54.0, 1.0),
 ('BBB', '2013B', 14992, 'CMA', 89.0, 1.0),
 ('BBB', '2013B', 14993, 'CMA', 124.0, 1.0),
 ('BBB', '2013B', 14994, 'CMA', 159.0, 1.0),
 ('BBB', '2013B', 14995, 'CMA', 187.0, 1.0),
 ('BBB', '2013B', 14984, 'TMA', 19.0, 5.0),
 ('BBB', '2013B', 14985, 'TMA', 47.0, 18.0),
 ('BBB', '2013B', 14986, 'TMA', 89.0, 18.0),
 ('BBB', '2013B', 14987, 'TMA', 124.0, 18.0),
 ('BBB', '2013B', 14988, 'TMA', 159.0, 18.0),
 ('BBB', '2013B', 14989, 'TMA', 187.0, 18.0),
 ('BBB', '2013B', 14990, 'Exam', None, 100.0),
 ('BBB', '2013J', 15003, 'CMA', 54.0, 1.0),
 ('BBB', '2013J', 15004, 'CMA', 96.0, 1.0),
 ('BBB', '2013J', 15005, 'CMA', 131.0, 1.0),
 ('BBB', '2013J', 15006, 'CMA', 166.0, 1.0),
 ('BBB', '2013J', 15007, 'CMA', 208.0, 1.0),

Kita juga bisa melihat kolom-kolom tersebut dalam bentuk pandas data frame

In [49]:
pd.read_sql('''SELECT * FROM assessments''', conn)

,code_module,code_presentation,id_assessment,assessment_type,date,weight
0,AAA,2013J,1752,TMA,19.0,10.0
1,AAA,2013J,1753,TMA,54.0,20.0
2,AAA,2013J,1754,TMA,117.0,20.0
3,AAA,2013J,1755,TMA,166.0,20.0
4,AAA,2013J,1756,TMA,215.0,30.0
...,...,...,...,...,...,...
1025,GGG,2014J,37443,CMA,229.0,0.0
1026,GGG,2014J,37435,TMA,61.0,0.0
1027,GGG,2014J,37436,TMA,124.0,0.0
1028,GGG,2014J,37437,TMA,173.0,0.0
1029,GGG,2014J,37444,Exam,229.0,100.0

Membuat tabel 'courses' dari data courses.csv dan menyimpan di database

In [20]:
orders = pd.read_csv('courses.csv') # load to DataFrame
orders.to_sql('courses', conn, if_exists='append', index = False) # write to sqlite table

Melihat semua kolom di tabel 'courses'

In [27]:
pd.read_sql('''SELECT * FROM courses''', conn)

   code_module code_presentation  module_presentation_length
0          AAA             2013J                         268
1          AAA             2014J                         269
2          BBB             2013J                         268
3          BBB             2014J                         262
4          BBB             2013B                         240
5          BBB             2014B                         234
6          CCC             2014J                         269
7          CCC             2014B                         241
8          DDD             2013J                         261
9          DDD             2014J                         262
10         DDD             2013B                         240
11         DDD             2014B                         241
12         EEE             2013J                         268
13         EEE             2014J                         269
14         EEE             2014B                         241
15         FFF             2013J                         268
16         FFF             2014J                         269
17         FFF             2013B                         240
18         FFF             2014B                         241
19         GGG             2013J                         261
20         GGG             2014J                         269
21         GGG             2014B                         241
22         AAA             2013J                         268
23         AAA             2014J                         269
24         BBB             2013J                         268
25         BBB             2014J                         262
26         BBB             2013B                         240
27         BBB             2014B                         234
28         CCC             2014J                         269
29         CCC             2014B                         241
30         DDD             2013J                         261
31         DDD             2014J                         262
32         DDD             2013B                         240
33         DDD             2014B                         241
34         EEE             2013J                         268
35         EEE             2014J                         269
36         EEE             2014B                         241
37         FFF             2013J                         268
38         FFF             2014J                         269
39         FFF             2013B                         240
40         FFF             2014B                         241
41         GGG             2013J                         261
42         GGG             2014J                         269
43         GGG             2014B                         241

Membuat tabel 'studentassessment' dari data studentAssessment.csv dan menyimpan di database

In [45]:
student_asses = pd.read_csv('studentAssessment.csv') # load to DataFrame
student_asses.to_sql('studentassessment', conn, if_exists='append', index = False) # write to sqlite table

Melihat semua kolom di tabel 'studentassessment'

In [46]:
pd.read_sql('''SELECT * FROM studentassessment''', conn)

        id_assessment  id_student  date_submitted  is_banked  score
0                1752       11391              18          0   78.0
1                1752       28400              22          0   70.0
2                1752       31604              17          0   72.0
3                1752       32885              26          0   69.0
4                1752       38053              19          0   79.0
...               ...         ...             ...        ...    ...
347819          37443      527538             227          0   60.0
347820          37443      534672             229          0  100.0
347821          37443      546286             215          0   80.0
347822          37443      546724             230          0  100.0
347823          37443      558486             224          0   80.0

[347824 rows x 5 columns]

Membuat tabel 'studentinfo' dari data studentInfo.csv dan menyimpan di database

In [24]:
student_info = pd.read_csv('studentInfo.csv') # load to DataFrame
student_info.to_sql('studentinfo', conn, if_exists='append', index = False) # write to sqlite table

Melihat semua kolom di tabel 'studentinfo'

In [30]:
pd.read_sql('''SELECT * FROM studentinfo''', conn)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
32588,GGG,2014J,2640965,F,Wales,Lower Than A Level,10-20,0-35,0,30,N,Fail
32589,GGG,2014J,2645731,F,East Anglian Region,Lower Than A Level,40-50%,35-55,0,30,N,Distinction
32590,GGG,2014J,2648187,F,South Region,A Level or Equivalent,20-30%,0-35,0,30,Y,Pass
32591,GGG,2014J,2679821,F,South East Region,Lower Than A Level,90-100%,35-55,0,30,N,Withdrawn
32592,GGG,2014J,2684003,F,Yorkshire Region,HE Qualification,50-60%,35-55,0,30,N,Distinction

Membuat tabel 'studentregist' dari data studentRegistration.csv dan menyimpan di database

In [25]:
student_regist = pd.read_csv('studentRegistration.csv') # load to DataFrame
student_regist.to_sql('studentregist', conn, if_exists='append', index = False) # write to sqlite table

Melihat semua kolom di tabel 'studentregist'

In [31]:
pd.read_sql('''SELECT * FROM studentregist''', conn)

,code_module,code_presentation,id_student,date_registration,date_unregistration
0,AAA,2013J,11391,-159.0,NaN
1,AAA,2013J,28400,-53.0,NaN
2,AAA,2013J,30268,-92.0,12.0
3,AAA,2013J,31604,-52.0,NaN
4,AAA,2013J,32885,-176.0,NaN
...,...,...,...,...,...
32588,GGG,2014J,2640965,-4.0,NaN
32589,GGG,2014J,2645731,-23.0,NaN
32590,GGG,2014J,2648187,-129.0,NaN
32591,GGG,2014J,2679821,-49.0,101.0
32592,GGG,2014J,2684003,-28.0,NaN

Membuat query untuk memperoleh data dengan kolom: id_student, region, code_module, assessment_type, score. Data yang diambil hanya dengan code_presentation 2014B

In [61]:
DataSQL = pd.read_sql('''SELECT sa.id_student, si.region, asm.code_module, asm.assessment_type, sa.score
                FROM studentassessment sa
                LEFT JOIN studentinfo si ON si.id_student = sa.id_student
                LEFT JOIN assessments asm ON asm.id_assessment = sa.id_assessment
                WHERE asm.code_presentation = '2014B'
                ''', conn)
DataSQL

        id_student                region code_module assessment_type  score
0            25997         London Region         BBB             CMA  100.0
1            25997         London Region         BBB             CMA  100.0
2            27891              Scotland         BBB             CMA  100.0
3            27891              Scotland         BBB             CMA  100.0
4            27891              Scotland         BBB             CMA  100.0
...            ...                   ...         ...             ...    ...
489535     2682002      Yorkshire Region         GGG             TMA   65.0
489536     2689480          North Region         GGG             TMA   55.0
489537     2689480          North Region         GGG             TMA   55.0
489538     2695362  East Midlands Region         GGG             TMA   78.0
489539     2695362  East Midlands Region         GGG             TMA   78.0

[489540 rows x 5 columns]

Menyimpan data frame ke dalam excel

In [62]:
nama_file = "NGChallenge3.xlsx"
DataSQL.to_excel(nama_file)
print("DataFrame ke Excel telah berhasil")

DataFrame ke Excel telah berhasil